variables:
  CODECOV_TOKEN: 202255eb-62eb-4b29-b065-0f832265e84f
  SKIP_SHTNS: 1

tests:
  image: fluiddyn/python3-stable
  script:
    - echo "SKIP_SHTNS $SKIP_SHTNS"
    - echo "GITLAB_CI $GITLAB_CI"
    - pip install -U tox --user
    - tox -e py36,codecov
