variables:
  CODECOV_TOKEN: 202255eb-62eb-4b29-b065-0f832265e84f

image: fluiddyn/python3-stable:heptapod

stages:
  - lint
  - build
  - test
  - deploy

validate_style:
  stage: lint
  before_script:
    - pip install black --user
  script:
    - black --diff --check fluiddyn fluiddoc
  allow_failure: true

build_docs:
  stage: build
  image: sphinxdoc/sphinx:5.3.0
  before_script:
    - pip install -e .[doc]
  script:
    - make -C doc
  artifacts:
    paths:
      - doc/_build/html
  needs: []

run_tests:
  stage: test
  before_script:
    - pip install -U pip tox --user
  script:
    - tox -e py36,codecov
  needs: []