variables:
  OMPI_ALLOW_RUN_AS_ROOT: "1"
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"

default:
  # for standard MR:
  # image: registry.heptapod.net:443/fluiddyn/fluiddyn/ci/default:stable
  # for MR modifying the Docker file:
  image: registry.heptapod.net:443/fluiddyn/fluiddyn/ci/$CI_COMMIT_HG_BRANCH:stable
  tags:
    - container-registry-push

stages:
  - image
  - lint
  - test
  - doc
  - deploy

# Build an image for the above tasks; this should be a scheduled job, as
# it is quite unnecessary to run on every invocation.
image:build:
  stage: image
  # comment these rules for MR modifying the Docker file
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "schedule"'
  #   - if: '$CI_BUILD_IMAGES == "1"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - ""
  script:
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --single-snapshot
      --cleanup
      --destination registry.heptapod.net:443/fluiddyn/fluiddyn/ci/$CI_COMMIT_HG_BRANCH:stable

validate_style:
  stage: lint
  script:
    - black --diff --check fluiddyn fluiddoc
  allow_failure: true

validate_min_version:
  stage: lint
  script:
    - vermin --no-parse-comments --lint --target=3.9 --no-tips  fluiddyn fluiddoc
  allow_failure: true

validate_imports:
  stage: lint
  script:
    - isort . --verbose --check-only --only-modified --diff
  allow_failure: true

test:run:
  stage: test
  script:
    - tox -e py39,codecov
  needs:
    - job: "image:build"
      optional: true
  artifacts:
    when: always
    paths:
      - pytest_result.xml
      - .coverage/index.html
    reports:
      junit: pytest_result.xml

doc:build:
  stage: doc
  image: sphinxdoc/sphinx:5.3.0
  before_script:
    - pip install -e .[doc]
  script:
    - make -C doc
  artifacts:
    paths:
      - doc/_build/html
  needs:
    - job: "image:build"
      optional: true

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "branch/default"'
  script:
    - mkdir public
    - cp -vr doc/_build/html/* public/
  dependencies:
    - doc:build
  needs: ["doc:build"]
  artifacts:
    paths:
      - public
