[project]
name = "fluiddyn"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
# use as `pixi run install-editable`
install-dependencies = "pixi install"
install-editable = {cmd = "pip install -e . -v --no-build-isolation --no-deps", depends_on = ["install-dependencies"]}

[dependencies]
h5py = ">=3.10.0"
distro = ">=1.9.0"
matplotlib = ">=3.8.2"
numpy = ">=1.26.3"
psutil = ">=5.2.1"
h5netcdf = ">=1.3.0"
pytest = ">=7.4.4"
scipy = ">=1.11.4"
pytest-cov = ">=4.1.0"
pillow = ">=10.2.0"
pyfftw = ">=0.13.1"
coverage = ">=7.4.0"
pulp = ">=2.8.0"
tomli = ">=2.0.1"
imageio = ">=2.33.1"
ipython = ">=8.20.0"
simpleeval = ">=0.9.13"

[host-dependencies]
python = ">=3.9"
pdm-backend = ">=2.1.8"
pip = ">=23.3.2"
editables = ">=0.3"
