
channels:
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - h5py
  - jupyter
  - matplotlib
  - pandas
  - imageio
  - pip:
    - sphinx
    - numpydoc
    - sphinx_rtd_theme
    - sphinxemoji
