
channels:
  - conda-forge

dependencies:
  - python=3.7
  - pip
  - numpy
  - h5py
  - pip:
    - jupyter
    - matplotlib
    - pandas
    - imageio
    - sphinx
    - numpydoc
    - sphinx_rtd_theme
    - sphinxemoji
